// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseExperimentsLib2.Entities;

[Index("FirstName", "LastName", Name = "IX_Authors_FirstName_LastName", IsUnique = true)]
public partial class Author
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(128)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(128)]
    public string LastName { get; set; }

    [InverseProperty("Author")]
    public virtual ICollection<AuthorBook> AuthorBooks { get; set; } = new List<AuthorBook>();
}