// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseExperimentsLib2.Entities;

[PrimaryKey("AuthorBooksId", "AuthorId")]
[Table("AuthorBook")]
[Index("AuthorId", Name = "IX_AuthorBook_AuthorId")]
public partial class AuthorBook
{
    [Key]
    public long AuthorBooksId { get; set; }

    [Key]
    public long AuthorId { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("AuthorBooks")]
    public virtual Author Author { get; set; }

    [ForeignKey("AuthorBooksId")]
    [InverseProperty("AuthorBooks")]
    public virtual Book AuthorBooks { get; set; }
}