// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseExperimentsLib2.Entities;

[Index("Name", Name = "IX_BookTypes_Name", IsUnique = true)]
public partial class BookType
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(128)]
    public string Name { get; set; }

    [InverseProperty("BookType")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}