// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseExperimentsLib2.Entities;

[Index("BookTypeId", Name = "IX_Books_BookTypeId")]
[Index("PublisherId", Name = "IX_Books_PublisherId")]
[Index("Title", "Year", Name = "IX_Books_Title_Year", IsUnique = true)]
public partial class Book
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(256)]
    public string Title { get; set; }

    public long BookTypeId { get; set; }

    public long PublisherId { get; set; }

    public int Year { get; set; }

    [InverseProperty("AuthorBooks")]
    public virtual ICollection<AuthorBook> AuthorBooks { get; set; } = new List<AuthorBook>();

    [ForeignKey("BookTypeId")]
    [InverseProperty("Books")]
    public virtual BookType BookType { get; set; }

    [ForeignKey("PublisherId")]
    [InverseProperty("Books")]
    public virtual Publisher Publisher { get; set; }
}